import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '@/styles/Clients.module.scss'
import {useEffect, useReducer, useState} from "react";
import {ClientData} from "@/types";
import {useRouter} from "next/router";

const inter = Inter({subsets: ['latin']})

import stateReducer, {PageProps, State, StateDispatch} from "@/reducers/stateReducer";



export default function Clients({state, dispatch}: PageProps) {

    let {clients, username} = state;

    useEffect(() => {
        // // update data on API:
        // fetch('/api/clients')
        //     .then(res => res.json())
        //     .then(data => dispatch({
        //         type: "CLIENT_READ",
        //         payload: data
        //     })    )

        dispatch({type: "SET_USERNAME", payload: "Ale"})
    }, [])

    useEffect(() => {
        if (clients) {
            // /api/clients         GET  read all clients
            // /api/clients         POST add a new client
            // /api/clients/:id     GET  fetch a client
            // /api/clients/:id     PUT  update a client
            // /api/clients/:id     DELETE

            let client: ClientData = {
                age: 0, id: 0, name: ""
            }


        }
    }, [])

    const router = useRouter();

    return (
        <>
            <Head>
                <title>Clients</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>

                <h1>Welcome, {username}</h1>
                {
                    clients.map(
                        (client, index) =>
                            <div key={index} className={styles.clientItem}>
                                <a


                                    href={`/clients/${client.id}`}
                                >
                                    <div>
                                        <h2>{client.name}</h2>
                                        {client.age}, ID={client.id}
                                    </div>
                                </a>

                                <div>
                                    <button
                                        onClick={e => dispatch({
                                            type: "CLIENT_DELETE", payload: client.id
                                        })}
                                    >Delete</button>
                                </div>
                                <div>
                                    <button
                                        onClick={e => router.push(`/clients/edit/${client.id}`) }
                                    >Update</button>
                                </div>
                            </div>
                    )
                }

                {/*<div className={styles.clientItem}>*/}
                {/*    <h2>John Doe</h2>*/}
                {/*    22, ID=1*/}
                {/*</div>*/}
                {/*<div className={styles.clientItem}>*/}
                {/*    <h2>John Doe</h2>*/}
                {/*    22, ID=1*/}
                {/*</div>*/}
            </main>
        </>
    )
}
