import '@/styles/globals.css'
import styles from '@/styles/Clients.module.scss'
import type { AppProps } from 'next/app'
import Head from "next/head";
import Link from "next/link";
import Navigation from "@/components/Navigation";

import stateReducer from "@/reducers/stateReducer";
import {useEffect, useReducer} from "react";


export default function App({ Component, pageProps }: AppProps) {

  const [
    state, // or just write state, and you'll use state.username and state.clients
    dispatch
  ] = useReducer(
      stateReducer,
      {username: "Alexandra", clients: []}
  );

  useEffect(() => {
    // update data on API:
    fetch('/api/clients')
        .then(res => res.json())
        .then(data => dispatch({
          type: "CLIENT_READ",
          payload: data
        })    )
  })

  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="keywords" content="nails schedule professional" />

      <title>Business</title>
    </Head>
    <Navigation />

    <main style={{minHeight: "100vh"}}>
      <Component
          {...pageProps}
          state={state}
          dispatch={dispatch}
      />
    </main>

    <footer>
      Welcome to my business
    </footer>
    </>
}
