import '@/styles/globals.css'
import styles from '@/styles/Clients.module.scss'
import type { AppProps } from 'next/app'
import Head from "next/head";
import Link from "next/link";
import Navigation from "@/components/Navigation";

export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="keywords" content="nails schedule professional" />

      <title>Business</title>
    </Head>
    <Navigation />

    <main style={{minHeight: "100vh"}}>
      <Component {...pageProps} />
    </main>

    <footer>
      Welcome to my business
    </footer>
    </>
}
